### ISSUE TITLE
Custom Widget ID is Invalid

### ISSUE THREAD

**Issue by ryancooper7** [modelberry/factory#73]
We are attempting to first Pull Models from a Master environment and then push models to a Dev environment. We are not seeing JSON object fields display properly when they are supposed to show the Frontify image selector widget. 

This is the annotated type returned from the Pull Models command:

`  /** @modelberry
   * - {@name Background Image Test}
   * - {@type Object}
   * - {@widgetId 5wHGALSJtz7y2EQOLfGhKH}
   * - {@widgetNamespace app}
   */
  backgroundImage?: string;`
  
  And this is what we see when we attempt to create content using the type after pushing the models:
  
  
![image](https://user-images.githubusercontent.com/17011548/231896949-1d9675ba-e345-42d0-8402-600f29ebc614.png)

**Comment by jaccomeijer** [comment]
Thx for reporting this, will have a look next week.

**Comment by jaccomeijer** [comment]
I've reproduced the error by adding the Frontify app and creating a JSON field. Pulling the model resulted in:

```js
  /** @modelberry
   * - {@name FrontifyJson}
   * - {@type Object}
   * - {@widgetId 5wHGALSJtz7y2EQOLfGhKH}
   * - {@widgetNamespace app}
   */
  frontifyJson?: string;
```

Pushing this model gave this error:

`Unknown field tag: @widgetNamespace. Valid field tags are: @description, @disabled, @ignore, @helpText, @itemsType, @itemsLinkType, @itemsValidations, @linkType, @locale, @localized, @name, @omitted, @required, @type, @validations, @widgetId`

Version [8.0.4](https://github.com/modelberry/factory/releases/tag/8.0.4) has the TSDoc tag `@widgetNamespace` added.

Pushing the model now works as expected. With one side effect. When pushing an existing (or new) JSON field, the field is unassigned from the Frontify app. Even when the `@widgetId` and `@widgetNamespace` are left out.

I expect the app to work when the field is reassigned. Not sure if this can be handled in a generic way with the Contentful API. Probably using `@ignore` once the field is created is best here.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/32537642/232602490-96d74ef1-00b5-47cc-a81d-e4e4a8e4a705.png">
